##################################################################
# +------------------------------------------------------------+ #
# |                   qTemplate Config                         | #
# |   Source:   https://github.com/QarthO/qTemplate/           | #
# |   Download: https://modrinth.com/plugin/qTemplate/         | #
# |   Donate:   https://quartzdev.gg/donate/                   | #
# |   Discord:  https://quartzdev.gg/discord/                  | #
# +------------------------------------------------------------+ #
##################################################################

# Default Config
schema-version: 1.0

# Requires '###.admin.updates' permission to be notified
# OPs can deny this permission to not be notified upon logging in
# Only checks when the server boots or someone with the permission logs in
# Note: A server restart is required to change this setting
# Default: true
check-updates: true

##################################################################
# +------------------------------------------------------------+ #
# |                          Section                           | #
# +------------------------------------------------------------+ #
##################################################################
